---
all:
  children:
    frontend:
      hosts:
        metrics-frontend:
          ansible_host: "{{ frontend_ip }}"  # Will be populated by terraform output
          ansible_user: root
          ansible_ssh_private_key_file: "~/.ssh/id_rsa"  # Update with your key
    
    backend:
      children:
        prometheus:
          hosts:
            metrics-prometheus:
              ansible_host: 192.168.1.10  # Update with your actual IP
              ansible_user: ubuntu
              ansible_ssh_private_key_file: "~/.ssh/id_rsa"
        
        grafana:
          hosts:
            metrics-grafana:
              ansible_host: 192.168.1.11  # Update with your actual IP
              ansible_user: ubuntu
              ansible_ssh_private_key_file: "~/.ssh/id_rsa"
        
        loki:
          hosts:
            metrics-loki:
              ansible_host: 192.168.1.12  # Update with your actual IP
              ansible_user: ubuntu
              ansible_ssh_private_key_file: "~/.ssh/id_rsa"
        
        alertmanager:
          hosts:
            metrics-alertmanager:
              ansible_host: 192.168.1.13  # Update with your actual IP
              ansible_user: ubuntu
              ansible_ssh_private_key_file: "~/.ssh/id_rsa"
        
        netbox:
          hosts:
            metrics-netbox:
              ansible_host: 192.168.1.14  # Update with your actual IP
              ansible_user: ubuntu
              ansible_ssh_private_key_file: "~/.ssh/id_rsa"
    
    hypervisors:
      children:
        proxmox:
          hosts:
            proxmox-01:
              ansible_host: 192.168.1.20  # Update with your actual IP
              ansible_user: root
              ansible_ssh_private_key_file: "~/.ssh/id_rsa"
        
        xcpng:
          hosts:
            xcpng-01:
              ansible_host: 192.168.1.30  # Update with your actual IP
              ansible_user: root
              ansible_ssh_private_key_file: "~/.ssh/id_rsa"
    
    linux:
      hosts:
        linux-server-01:
          ansible_host: 192.168.1.40  # Update with your actual IP
          ansible_user: ubuntu
          ansible_ssh_private_key_file: "~/.ssh/id_rsa"
    
    docker:
      hosts:
        docker-host-01:
          ansible_host: 192.168.1.50  # Update with your actual IP
          ansible_user: ubuntu
          ansible_ssh_private_key_file: "~/.ssh/id_rsa"
    
    kiosks:
      hosts:
        kiosk-01:
          ansible_host: 192.168.1.60  # Update with your actual IP
          ansible_user: ubuntu
          ansible_ssh_private_key_file: "~/.ssh/id_rsa"
    
    windows:
      hosts:
        windows-server-01:
          ansible_host: 192.168.1.70  # Update with your actual IP
          ansible_user: Administrator
          ansible_password: "{{ windows_password }}"  # Will be populated from vars
          ansible_connection: winrm
          ansible_winrm_server_cert_validation: ignore
