---
all:
  children:
    frontend:
      hosts:
        metrics-frontend:
          ansible_host: "149.28.169.127"
          ansible_user: root
          ansible_ssh_private_key_file: "~/.ssh/id_rsa"  # Update with your key path
    
    backend:
      children:
        prometheus:
          hosts:
            metrics-prometheus:
              ansible_host: 192.168.1.10  # Update with your actual IP
              ansible_user: ubuntu
              ansible_ssh_private_key_file: "~/.ssh/id_rsa"
