    - name: Generate WireGuard private key
      shell: wg genkey
      register: wireguard_private_key
      changed_when: false

    - name: Generate WireGuard public key
      shell: echo "{{ wireguard_private_key.stdout }}" | wg pubkey
      register: wireguard_public_key
      changed_when: false

    - name: Ensure WireGuard module is loaded
      shell: modprobe wireguard
      changed_when: false
      ignore_errors: true

    - name: Configure WireGuard
      template:
        src: ../roles/wireguard/templates/wg0.conf.j2
        dest: /opt/metrics/wireguard/wg0.conf
        owner: root
        group: root
        mode: 0600

    - name: Enable WireGuard
      copy:
        content: |
          [Unit]
          Description=WireGuard interface wg0
          After=network.target

          [Service]
          Type=oneshot
          ExecStart=/usr/bin/wg-quick up /opt/metrics/wireguard/wg0.conf
          ExecStop=/usr/bin/wg-quick down /opt/metrics/wireguard/wg0.conf
          RemainAfterExit=yes

          [Install]
          WantedBy=multi-user.target
        dest: /etc/systemd/system/wg-quick@wg0.service
        owner: root
        group: root
        mode: 0644

    - name: Display WireGuard configuration
      debug:
        msg: "WireGuard private key is {{ wireguard_private_key.stdout }} and public key is {{ wireguard_public_key.stdout }}"

    - name: Start and enable WireGuard
      systemd:
        name: wg-quick@wg0
        state: started
        enabled: yes
        daemon_reload: yes
      register: wireguard_service_result
      ignore_errors: true

    - name: Check WireGuard service status if it failed
      shell: "systemctl status wg-quick@wg0.service"
      register: wg_status
      when: wireguard_service_result is failed
      ignore_errors: true

    - name: Display WireGuard service status if it failed
      debug:
        msg: "{{ wg_status.stdout_lines | default('No output') }}"
      when: wg_status is defined

    - name: Continue despite WireGuard failure
      debug:
        msg: "WireGuard setup failed but continuing with deployment. You may need to set it up manually later."
      when: wireguard_service_result is failed